#ifndef MOTOR_CONFIG_H
#define MOTOR_CONFIG_H

#define MOTOR_POLE_PAIR_NUMBER  50
#define MOTOR_PHASE_RESISTANCE  0.88f // [Ohms]
#define MOTOR_KV_RATING         NOT_SET // [RPM/V] (RMS value)
#define MOTOR_PHASE_INDUCTANCE  0.0034f // [H]

#endif // MOTOR_CONFIG_H